name: t3aisat
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.7+43

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mapbox_maps_flutter: ^2.4.1
  xml: ^6.5.0
  geotypes: ^0.0.2
  geobase: ^1.4.0+1
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  logging: ^1.3.0
  path_provider: ^2.1.5
  path: ^1.9.0
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.0
  geolocator: ^13.0.2
  http: ^1.2.2
  image: ^4.3.0
  intl: ^0.19.0
  native_exif: ^0.6.0
  camera: ^0.11.0+2
  video_player: ^2.9.2
  saver_gallery: ^4.0.0
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  photo_manager: ^3.6.3
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  vibration: ^2.0.1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  flutter_markdown: ^0.7.4+3
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.3
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  collection: ^1.18.0
  http_parser: ^4.0.2
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  string_scanner: ^1.2.0
  test_api: ^0.7.2
  vm_service: ^14.2.5
  build_runner: ^2.4.13
  objectbox_generator: ^4.0.3
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - .env.development
    - .env.production
    - assets/fonts/roboto_black/Roboto-Black_100_size_white_color.ttf.zip
    - assets/fonts/roboto_bold/Roboto-Bold-20-size-white-color.ttf.zip
    - assets/fonts/roboto/Roboto-Bold.ttf
    - assets/documents/privacy_policy_t3aisat.md

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icon/app_icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon/app_icon.png'

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/icon/app_icon.png'
  android: true
  ios: true
  fullscreen: true
